#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     nothing,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Hammer,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     Sweeper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     Left,          tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    Piston,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    RightServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    LeftServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


const int grabberDown = 40;
const int grabberUp = -60;

void setGrabber(int a) {
	servo[RightServo] = 190 + a;
	servo[LeftServo] = 153 - a;
}

void initializeRobot() {
	setGrabber(grabberUp);
  return;
}

task main() {
  initializeRobot();
  waitForStart();
 	motor[Left] = 30;
  motor[Right] = 30;
  wait1Msec(3000);
  motor[Left] = 0;
  motor[Right] = 0;

  motor[Left] = 50;
	motor[Right] = -50;
	wait1Msec(2000);
	motor[Left] = 0;
	motor[Right] = 0;

  motor[Lift] = 30;
  wait1Msec(2500);
  motor[Lift] = 0;
  motor[Left] = -50;
  motor[Right] = -50;
  wait1Msec(1000);
  setGrabber(grabberDown);
  wait1Msec(500);
  motor[Left] = 0;
  motor[Right] = 0;
  wait1Msec(2000);
  for(int i = 0; i < 3; i++) {
  	motor[Left] = 50;
  	motor[Right] = 50;
  	wait1Msec(200);
  	motor[Left] = -50;
  	motor[Right] = -50;
  	wait1Msec(200);
  	i++;
	}
	motor[Left] = 0;
	motor[Right] = 0;
	motor[Hammer] = 80;
 	wait1Msec(2600);
  motor[Hammer] = 0;
  servo[Piston] = 200;
  wait1Msec(1000);
  motor[Hammer] = 80;
 	wait1Msec(1500);
  motor[Hammer] = 0;

 motor[Left] = 50;
 wait1Msec(1000); //1500
 motor[Left] = 0;
wait1Msec(500);
motor[Left] = 50;
motor[Right] = 50;
wait1Msec(5500);
motor[Left] = 0;
motor[Right] = 0;
}
