#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     nothing,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Hammer,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     Sweeper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     Left,          tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    RightServo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    LeftServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    Piston,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


const int grabberDown = 40;
const int grabberUp = -60;
const int pistonDown = 110;
const int pistonUp = 200;

int sign(int num)
{
	if(num<0)
	{
		return  -1;
		} else	{
		return 1;
	}
}
typedef struct
{
	bool pressed;
	bool run;
} servobuttons;

typedef enum
{
	btn_X=1,
	btn_A=2,
	btn_B=3,
	btn_Y=4,
	btn_LB=5,
	btn_RB=6,
	btn_LT=7,
	btn_RT=8,
	btn_BACK=9,
	btn_START=10
} joybtn;

void setGrabber(int a)
{
	servo[RightServo] = 190+a;
	servo[LeftServo] = 153-a;
}

void initializeRobot()
{
	setGrabber(grabberDown);
	servo[Piston] = pistonDown;
}
task shoot()
{
	while(true)
	{
		if(joy2Btn(btn_RT))
		{
			motor[Hammer] = 100;
		}
		else if(joy2Btn(btn_RB))
		{
			motor[Hammer] = -70;
		}
		else
		{
			motor[Hammer] = 0;
		}
	}
}

task main()
{
	servobuttons sweep;
	sweep.run = false;
	initializeRobot();
	waitForStart();
	StartTask(shoot);
	while(true)
	{
		if(abs(joystick.joy1_y1) > 15 || abs(joystick.joy1_x1) > 15)
		{
			motor[Right] = joystick.joy1_y1-joystick.joy1_x1;
			motor[Left] = joystick.joy1_y1+joystick.joy1_x1;
		}
		else
		{
			motor[Left] = 0;
			motor[Right] = 0;
		}
		if(joy1Btn(btn_B) && !sweep.pressed)
		{
			sweep.run = !sweep.run;
			sweep.pressed = true;
		}
		if(!joy1Btn(btn_B))
			sweep.pressed = false;
		if(joy1Btn(btn_A))
			motor[Sweeper] = -80;
		else if(sweep.run)
			motor[Sweeper] = 80;
		else
			motor[Sweeper] = 0;
		if(joy2Btn(btn_Y))
			setGrabber(grabberUp);
		else if(joy2Btn(btn_A))
			setGrabber(grabberDown);
		if(joy2Btn(btn_START))
			servo[Piston] = pistonUp;
		else
			servo[Piston] = pistonDown;
		if(joy2Btn(btn_LB))
			motor[Lift] = 100;
		else if (joy2Btn(btn_BACK))
			motor[Lift] = -80;
		else
			motor[Lift] = 0;
	}
}
